### PR TITLE
OCM-3042: Remove ability to manage default machinepool via cluster

### PR DESCRIPTION
**Pull request by JohnStrunk**
This makes the default machine pool fields in the cluster resource only used for creating the initial cluster. They cannot be used to update the default worker pool.

- Associated fields cannot be changed
- Fields are not read back from OCM into the state

NOTE: After merging this PR, it will not be possible to manage the default machinepool until the rest of [OCM-3042](https://issues.redhat.com//browse/OCM-3042) is complete.

### CODE REVIEW

**Comment by JohnStrunk** [comment]
I seem to have broken the e2e suite w/ this PR, but I'm having trouble figuring out why...

From the CI logs:
```
[31m│[0m [0m[1m[31mError: [0m[0m[1mValue cannot be changed[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with rhcs_cluster_rosa_classic.rosa_sts_cluster,
[31m│[0m [0m  on main.tf line 78, in resource "rhcs_cluster_rosa_classic" "rosa_sts_cluster":
[31m│[0m [0m  78: resource "rhcs_cluster_rosa_classic" "rosa_sts_cluster" [4m{[0m[0m
[31m│[0m [0m
[31m│[0m [0mAttributeName("compute_machine_type") is blocked for updating
[31m╵[0m[0m
2023-08-03T16:45:11.724Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-08-03T16:45:11.726Z [DEBUG] provider: plugin process exited: path=.terraform/providers/terraform.local/local/rhcs/1.1.0/linux_amd64/terraform-provider-rhcs pid=3071
2023-08-03T16:45:11.726Z [DEBUG] provider: plugin exited
```

I believe this change is what's triggering the error:
https://github.com/terraform-redhat/terraform-provider-rhcs/pull/227/files?diff=unified#diff-107822305b90ffba3097cc6ce67f08cf939d863c3ab926e1c9c20d2856392572L241-R251

However, the above error seems to be happening during the destroy:
```
+ HOME=/root
+ terraform destroy -auto-approve
2023-08-03T16:45:08.156Z [INFO]  Terraform version: 1.5.4
2023-08-03T16:45:08.156Z [DEBUG] using github.com/hashicorp/go-tfe v1.26.0
2023-08-03T16:45:08.156Z [DEBUG] using github.com/hashicorp/hcl/v2 v2.16.2
2023-08-03T16:45:08.156Z [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.0
2023-08-03T16:45:08.156Z [DEBUG] using github.com/zclconf/go-cty v1.12.2
2023-08-03T16:45:08.156Z [INFO]  Go runtime version: go1.20
2023-08-03T16:45:08.156Z [INFO]  CLI args: []string{"terraform", "destroy", "-auto-approve"}
```

Is it possible that destroy is using a different tf config than was used to create the cluster?

[Full log](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/terraform-redhat_terraform-provider-rhcs/227/pull-ci-terraform-redhat-terraform-provider-rhcs-main-managed-oidc-config-e2e-presubmit/1687132856049995776/build-log.txt)

Not sure to ping w/ an understanding of the CI... maybe: @nirarg @osherdp

**Comment by osherdp** [comment]
@nirarg @sagidayan I remember in [OCM-278](https://issues.redhat.com/browse/OCM-278) we intended to store the tfvars file as an artifact, no idea why it didn't happen
In this kind of error it can help a bit investigating the problem

**Comment by nirarg** [comment]
> Is it possible that destroy is using a different tf config than was used to create the cluster?

As far as I understand the `compute_machine_type` doesn't change, both don't set it so default value is used
@amalykhi @AsherShoshan can you please advice on this?

**Comment by amalykhi** [comment]
hm. compute type can't be changed, @nirarg 

May be same issue as we had for imdsv2? if it can't be changed and state was null, and now it takes default value. Need to verify the state

**Comment by nirarg** [comment]
> May be same issue as we had for imdsv2? if it can't be changed and state was null, and now it takes default value. Need to verify the state

Thanks @amalykhi 
I don't think its the same issue, in `imdsv2` the issue was that the attribute wasn't computed, which is not the case here

**Comment by JohnStrunk** [comment]
/close
In favor of #228

**Pull request closed without merging**
