### PR TITLE
OCM-2637: [BREAKING] htpasswd IDP user list

### PR DESCRIPTION
**Pull request by sagidayan**
This commit changes the way the user is passing user credentials into htpasswd IDP resource.

Before this commit, a single username and password was passed. 
This commit/PR moves to `users`, a list of user credentials.

Updated docs and examples as well.

### CODE REVIEW

**Comment by nirarg** [comment]
Thank you @sagidayan ,
That is look good
Did you check how it acts after provider update?
1. Create cluster before change
2. Create htpasswd IDP
3. update provider
4. Change manually the username/password format in the manifest
I'm aware that this can't be updated after creation but need to check if other partd in the manifest are functional.
Is it enough? does the terraform work as expected after this change?

**Comment by nirarg** [comment]
@bardielle please also review this

**Comment by sagidayan** [comment]
@nirarg 
Since there is no update implementation, tf will return `Error: Provider produced inconsistent result after apply`. This is to be expected, since tf will try to update the resource. 
As mentioned in the title of this PR `BREAKING`.

You can, however, destroy the old one, update the .tf file to the new schema and apply. Should result in a working IDP. Plus, so far, you could only have one user in the IDP, and we are not GA, So don't see the harm.
Worst case, you recreate an IDP. (one user will "suffer") for (less than) 10 sec.

This will also not work if we do support the old `username/password` attributes for compatibility, TF will still try to update and will return the same error.

Thoughts?

Actually, after #226, the error will be as described there (Update not supported)

**Comment by nirarg** [comment]
Ok, got it
So as far as I understand:
1. As long as the user doesn't run terraform apply on the manifest, the old user work
2. In case user want to apply any change in the manifest (not related to the IDP) he must destroy the existing htpasswd IDPs and create new ones with the new username/password format

Need to document this known limitation
@EricPonvelle @arendej FYI

/hold cancel

**Comment by sagidayan** [comment]
> Ok, got it So as far as I understand:
> 
> 1. As long as the user doesn't run terraform apply on the manifest, the old user work
> 2. In case user want to apply any change in the manifest (not related to the IDP) he must destroy the existing htpasswd IDPs and create new ones with the new username/password format
> 
> Need to document this known limitation @EricPonvelle @arendej FYI
> 
> /hold cancel

Correct.

**Pull request merged**
