### PR TITLE
OCM-10805 | ci: Automate ids:76499,76500,76501

### PR DESCRIPTION
**Pull request by radtriste**
**Logs:**
- [76500](https://privatebin.corp.redhat.com/?ab259f50a1ff8223#7Sbwt3nqQJARvqcGP1CudGpTFwWF3R1Kmd9zHr4BQgTU)
- [76499](https://privatebin.corp.redhat.com/?eba94e9e9c7264d7#4d6QRHuNyDp2KhoH1mDu7oTqHoCKPwQX8Vm8VT4dMHMd)
- [76501](https://privatebin.corp.redhat.com/?5a5a8445dc3ae115#38jhRgjuQFQ8uYpQuN1ax91hXdzhqsnB3tFfagxXWWur)

**Which issue(s) this PR fixes** 
https://issues.redhat.com/browse/OCM-10805

**Change type**
- [ ] New feature
- [ ] Bug fix
- [ ] Build
- [x] CI
- [ ] Documentation
- [ ] Performance
- [ ] Refactor
- [ ] Style
- [ ] Unit tests
- [ ] Subsystem tests

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.

### CODE REVIEW

**Review by ciaranRoche — APPROVED** [review]
/lgtm

**Comment by radtriste** [comment]
Issue in `rosa-sts-private` is not related

**Pull request merged**
