### PR TITLE
OCM-6031 | feat: allow to edit component routes of ingress

### PR DESCRIPTION
**Pull request by gdbranco**
[OCM-6031](https://issues.redhat.com//browse/OCM-6031)

**Change type**
- [x] New feature
- [ ] Bug fix
- [ ] Build
- [ ] CI
- [x] Documentation
- [ ] Performance
- [ ] Refactor
- [ ] Style
- [ ] Unit tests
- [x] Subsystem tests

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.

### CODE REVIEW

**Comment by gdbranco** [comment]
/hold
Until we have 1.6.0

**Review by ciaranRoche — APPROVED** [review]
/lgtm

**Review by ciaranRoche — APPROVED** [review]
/lgtm

**Pull request merged**
