### PR TITLE
OCM-8460 | ci: Fix machinepool testing

### PR DESCRIPTION
**Pull request by radtriste**
**What this PR does / why we need it**:
Fix testing on HCP machinepool

**Which issue(s) this PR fixes**
https://issues.redhat.com/browse/OCM-8460

**Change type**
- [ ] New feature
- [ ] Bug fix
- [ ] Build
- [x] CI
- [ ] Documentation
- [ ] Performance
- [ ] Refactor
- [ ] Style
- [ ] Unit tests
- [ ] Subsystem tests

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.

### CODE REVIEW

**Comment by radtriste** [comment]
@deepsm007 Since your intervention, I have this Konflux check which prevents the PR to be merged. Can you have a look ?

**Comment by deepsm007** [comment]
User deepsm007 is not allowed to trigger CI via pull_request on this repo., it is requesting approval from owners or you can skip the test I triggered

**Pull request closed without merging**
