### PR TITLE
OCM-8697 | test: update case ids:65961, 73154, 66408, 66410

### PR DESCRIPTION
**Pull request by patriksuba**
Created new password generation for Admin and IDP HTPasswd passwords

**What this PR does / why we need it**:
Creation od IDP HTPasswd users occasionally failed with error: Attribute htpasswd.users[1].password password must contain lowercase\ncharacters, got: 1T/ETW4EZ65SX9G", }. 
The PR improve the way we generate password.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story (OCM-xxxx)*:
Fixes #8697
[OCM-8697](https://issues.redhat.com//browse/OCM-8697)

**Change type**
- [ ] New feature
- [x] Bug fix
- [ ] Build
- [ ] CI
- [ ] Documentation
- [ ] Performance
- [ ] Refactor
- [ ] Style
- [ ] Unit tests
- [ ] Subsystem tests

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.

### CODE REVIEW

**Review by robpblake — APPROVED** [review]
/lgtm

**Comment by radtriste** [comment]
@robpblake @ciaranRoche Here we still have the Konflux check as well.

**Pull request merged**
