### PR TITLE
Release 1.0.5

### PR DESCRIPTION
**Pull request by bardielle**
See the file CHANGELOG for details.

### CODE REVIEW

**Comment by bardielle** [comment]
/override ci/prow/managed-oidc-config-e2e-presubmit ci/prow/unmanaged-oidc-config-e2e-presubmit

**Comment by sagidayan** [comment]
/override ci/prow/managed-oidc-config-e2e-presubmit ci/prow/unmanaged-oidc-config-e2e-presubmit

**Pull request merged**
