### PR TITLE
OCM-5397 | chore: bump ocm-commons

### PR DESCRIPTION
**Pull request by gdbranco**
Related issue: [OCM-5397](https://issues.redhat.com//browse/OCM-5397)

### CODE REVIEW

**Comment by xueli181114** [comment]
`time="2024-01-09T12:36:47Z" level=error msg="Initializing the backend...\nInitializing modules...\nDownloading registry.terraform.io/terraform-redhat/rosa-sts/aws 0.0.15 for create_account_roles...\n\nError: Failed to download module\n\n  on main.tf line 30:\n  30: module \"create_account_roles\" {\n\nCould not download module \"create_account_roles\" (main.tf:30) source code\nfrom\n\"git::https://github.com/terraform-redhat/terraform-aws-rosa-sts?ref=v0.0.15\":\nerror downloading\n'https://github.com/terraform-redhat/terraform-aws-rosa-sts?ref=v0.0.15':\n/usr/bin/git exited with 128: Cloning into\n'.terraform/modules/create_account_roles'...\nerror: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500\nfatal: expected flush after ref listing\n.\n"`
Anything wrong happen to the module?

**Comment by xueli181114** [comment]
Multiple times that cluster creation failed at timeout. The cluster cannot get ready in 2 hours.

**Comment by xueli181114** [comment]
Failed at cluster operator waiting. Timeout all the time. It's OCP issue not related to rhcs. QE will make cluster operator wait optional and disable from presubmit testing jobs. Can be retest soon.

**Comment by gdbranco** [comment]
Taking some liberty to merge as it had been approved multiple times before and the tests are now passing

**Pull request merged**
