### PR TITLE
OCM-10019 | ci: update the OWNERS file

### PR DESCRIPTION
**Pull request by xueli181114**
**What this PR does / why we need it**:
update the OWNERS file of tests package
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story (OCM-xxxx)*:
Fixes #
[OCM-10019](https://issues.redhat.com//browse/OCM-10019)
**Change type**
- [ ] New feature
- [ ] Bug fix
- [ ] Build
- [x] CI
- [ ] Documentation
- [ ] Performance
- [ ] Refactor
- [ ] Style
- [ ] Unit tests
- [ ] Subsystem tests

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.

### CODE REVIEW

**Review by ciaranRoche — APPROVED** [review]
/lgtm

**Review by radtriste — COMMENTED** [review]
/lgtm

**Comment by radtriste** [comment]
@ciaranRoche could you add `jerichokeyne` and `aaraj7` to the members of the `terraform-redhat` org ?

**Pull request merged**
