### PR TITLE
OCM-6885 | fix: should not allow to edit tags on mp of HCP

### PR DESCRIPTION
**Pull request by gdbranco**
[OCM-6885](https://issues.redhat.com//browse/OCM-6885)

Relies on parameter to fetch user tags only, excluding system tags the customer might not know about. This helps in making sure that customer is able to provide all cluster plus new machine tags within the management file

**Change type**
- [ ] New feature
- [x] Bug fix
- [ ] Build
- [ ] CI
- [x] Documentation
- [ ] Performance
- [ ] Refactor
- [ ] Style
- [ ] Unit tests
- [x] Subsystem tests

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.

### CODE REVIEW

**Comment by gdbranco** [comment]
/hold

Holding until we have final 1.6.0 released

**Review by ciaranRoche — APPROVED** [review]
/lgtm

**Pull request merged**
