### PR TITLE
OCM-6960 | ci: Fix failure of @OCP-63316

### PR DESCRIPTION
**Pull request by xueli181114**
**What this PR does / why we need it**:
This is a PR fix the CI failure in [job](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-f3/1770776994649214976)
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story (OCM-xxxx)*:
Fixes #[OCM-6960](https://issues.redhat.com//browse/OCM-6960)

**Change type**
- [ ] New feature
- [ ] Bug fix
- [ ] Build
- [x] CI
- [ ] Documentation
- [ ] Performance
- [ ] Refactor
- [ ] Style
- [ ] Unit tests
- [ ] Subsystem tests

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.

### CODE REVIEW

**Comment by xueli181114** [comment]
@radtriste @jameszwang Can you review?

**Comment by xueli181114** [comment]
lixue@Xue-Lis-MacBook-Pro terraform-provider-rhcs % ginkgo -focus @OCP-63316 tests/e2e
time="2024-03-22T17:42:24+08:00" level=info msg="Running against env staging with gateway url https://api.stage.openshift.com"
time="2024-03-22T17:42:24+08:00" level=info msg="Loaded cluster profile configuration from profile rosa-sts-ad : map[additional_sg_number:4 admin_enabled:true autoscale:true byok:true byovpc:true ccs:true channel_group:stable cloud_provider:aws cluster_type:rosa-classic compute_machine_type:m5.2xlarge etcd_encryption:true fips:false imdsv2:required kms_key_arn:true labeling:true major_version:4.14 multi_az:true oidc_config:un-managed private:false private_link:false product_id:rosa proxy:true region:ap-northeast-1 sts:true tagging:true unified_acc_role_path:/unified/ version: version_pattern:latest worker_disk_size:200 zones:]"
Running Suite: e2e tests suite - /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/e2e
================================================================================================
Random Seed: 1711100538

Will run 1 of 59 specs
time="2024-03-22T17:42:24+08:00" level=info msg="Loaded cluster profile configuration from profile rosa-sts-ad : map[additional_sg_number:4 admin_enabled:true autoscale:true byok:true byovpc:true ccs:true channel_group:stable cloud_provider:aws cluster_type:rosa-classic compute_machine_type:m5.2xlarge etcd_encryption:true fips:false imdsv2:required kms_key_arn:true labeling:true major_version:4.14 multi_az:true oidc_config:un-managed private:false private_link:false product_id:rosa proxy:true region:ap-northeast-1 sts:true tagging:true unified_acc_role_path:/unified/ version: version_pattern:latest worker_disk_size:200 zones:]"
time="2024-03-22T17:42:24+08:00" level=info msg="Running terraform init against the dir /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/rhcs/clusters/rosa-classic"
time="2024-03-22T17:42:29+08:00" level=info msg="Running terraform output against the dir: /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/rhcs/clusters/rosa-classic"
SSSSSStime="2024-03-22T17:42:31+08:00" level=info msg="Loaded cluster profile configuration from profile rosa-sts-ad : map[additional_sg_number:4 admin_enabled:true autoscale:true byok:true byovpc:true ccs:true channel_group:stable cloud_provider:aws cluster_type:rosa-classic compute_machine_type:m5.2xlarge etcd_encryption:true fips:false imdsv2:required kms_key_arn:true labeling:true major_version:4.14 multi_az:true oidc_config:un-managed private:false private_link:false product_id:rosa proxy:true region:ap-northeast-1 sts:true tagging:true unified_acc_role_path:/unified/ version: version_pattern:latest worker_disk_size:200 zones:]"
time="2024-03-22T17:42:31+08:00" level=info msg="Running terraform init against the dir /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/aws/add-account-roles/rosa-classic"
time="2024-03-22T17:42:40+08:00" level=info msg="Running terraform apply against the dir: /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/aws/add-account-roles/rosa-classic with args [-var url=https://api.stage.openshift.com -var channel_group=stable -var account_role_prefix=OCP-63316 -var rhcs_environment=staging -var openshift_version=4.14]"
time="2024-03-22T17:42:53+08:00" level=info msg="Recording tfvars file /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/aws/add-account-roles/rosa-classic/terraform.tfvars"
time="2024-03-22T17:42:53+08:00" level=info msg="Running terraform output against the dir: /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/aws/add-account-roles/rosa-classic"
time="2024-03-22T17:42:55+08:00" level=info msg="Running terraform destroy against the dir: /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/aws/add-account-roles/rosa-classic"
time="2024-03-22T17:43:10+08:00" level=info msg="Deleting tfvars file /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/aws/add-account-roles/rosa-classic/terraform.tfvars"
time="2024-03-22T17:43:10+08:00" level=info msg="Running terraform destroy against the dir: /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/aws/add-account-roles/rosa-classic"
•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
P [PENDING]
TF Test Verfication/Post day 1 tests Author:xueli-Critical-OCP-69145 @OCP-69145 @xueli Apply to change security group will be forbidden [NonHCPCluster]
/Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/e2e/verfication_post_day1_test.go:261
------------------------------
SSSSSSS

Ran 1 of 59 Specs in 50.680 seconds
SUCCESS! -- 1 Passed | 0 Failed | 1 Pending | 57 Skipped

**Comment by xueli181114** [comment]
```
lixue@Xue-Lis-MacBook-Pro terraform-provider-rhcs % ginkgo -focus @OCP-63316 tests/e2e
time="2024-03-22T17:42:24+08:00" level=info msg="Running against env staging with gateway url https://api.stage.openshift.com"
time="2024-03-22T17:42:24+08:00" level=info msg="Loaded cluster profile configuration from profile rosa-sts-ad : map[additional_sg_number:4 admin_enabled:true autoscale:true byok:true byovpc:true ccs:true channel_group:stable cloud_provider:aws cluster_type:rosa-classic compute_machine_type:m5.2xlarge etcd_encryption:true fips:false imdsv2:required kms_key_arn:true labeling:true major_version:4.14 multi_az:true oidc_config:un-managed private:false private_link:false product_id:rosa proxy:true region:ap-northeast-1 sts:true tagging:true unified_acc_role_path:/unified/ version: version_pattern:latest worker_disk_size:200 zones:]"
Running Suite: e2e tests suite - /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/e2e
================================================================================================
Random Seed: 1711100538

Will run 1 of 59 specs
time="2024-03-22T17:42:24+08:00" level=info msg="Loaded cluster profile configuration from profile rosa-sts-ad : map[additional_sg_number:4 admin_enabled:true autoscale:true byok:true byovpc:true ccs:true channel_group:stable cloud_provider:aws cluster_type:rosa-classic compute_machine_type:m5.2xlarge etcd_encryption:true fips:false imdsv2:required kms_key_arn:true labeling:true major_version:4.14 multi_az:true oidc_config:un-managed private:false private_link:false product_id:rosa proxy:true region:ap-northeast-1 sts:true tagging:true unified_acc_role_path:/unified/ version: version_pattern:latest worker_disk_size:200 zones:]"
time="2024-03-22T17:42:24+08:00" level=info msg="Running terraform init against the dir /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/rhcs/clusters/rosa-classic"
time="2024-03-22T17:42:29+08:00" level=info msg="Running terraform output against the dir: /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/rhcs/clusters/rosa-classic"
SSSSSStime="2024-03-22T17:42:31+08:00" level=info msg="Loaded cluster profile configuration from profile rosa-sts-ad : map[additional_sg_number:4 admin_enabled:true autoscale:true byok:true byovpc:true ccs:true channel_group:stable cloud_provider:aws cluster_type:rosa-classic compute_machine_type:m5.2xlarge etcd_encryption:true fips:false imdsv2:required kms_key_arn:true labeling:true major_version:4.14 multi_az:true oidc_config:un-managed private:false private_link:false product_id:rosa proxy:true region:ap-northeast-1 sts:true tagging:true unified_acc_role_path:/unified/ version: version_pattern:latest worker_disk_size:200 zones:]"
time="2024-03-22T17:42:31+08:00" level=info msg="Running terraform init against the dir /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/aws/add-account-roles/rosa-classic"
time="2024-03-22T17:42:40+08:00" level=info msg="Running terraform apply against the dir: /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/aws/add-account-roles/rosa-classic with args [-var url=https://api.stage.openshift.com -var channel_group=stable -var account_role_prefix=OCP-63316 -var rhcs_environment=staging -var openshift_version=4.14]"
time="2024-03-22T17:42:53+08:00" level=info msg="Recording tfvars file /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/aws/add-account-roles/rosa-classic/terraform.tfvars"
time="2024-03-22T17:42:53+08:00" level=info msg="Running terraform output against the dir: /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/aws/add-account-roles/rosa-classic"
time="2024-03-22T17:42:55+08:00" level=info msg="Running terraform destroy against the dir: /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/aws/add-account-roles/rosa-classic"
time="2024-03-22T17:43:10+08:00" level=info msg="Deleting tfvars file /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/aws/add-account-roles/rosa-classic/terraform.tfvars"
time="2024-03-22T17:43:10+08:00" level=info msg="Running terraform destroy against the dir: /Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/tf-manifests/aws/add-account-roles/rosa-classic"
•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
P [PENDING]
TF Test Verfication/Post day 1 tests Author:xueli-Critical-OCP-69145 @OCP-69145 @xueli Apply to change security group will be forbidden [NonHCPCluster]
/Users/lixue/Workspace/ocm-tf/terraform-provider-rhcs/tests/e2e/verfication_post_day1_test.go:261
------------------------------
SSSSSSS

Ran 1 of 59 Specs in 50.680 seconds
SUCCESS! -- 1 Passed | 0 Failed | 1 Pending | 57 Skipped
```

**Review by radtriste — APPROVED** [review]

**Pull request merged**
