### PR TITLE
OCM-2644: Recreate machine pool if it was deleted from other client.

### PR DESCRIPTION
**Pull request by sagidayan**
This PR adds the ability to reconcile a machine pool that was created by TF, but then was removed via a different method, Not via terraform.

In this case, And if the user still has the machine pool resource in his `.tf` files. Upon an `apply` the provider will re-create the pool. 

Before this PR, the provider would have error out, since it could not find the machine pool defined in the state.

### CODE REVIEW

**Comment by nirarg** [comment]
/approve
@bardielle please take a look

**Comment by sagidayan** [comment]
/hold

refactoring

**Pull request merged**
